### ISSUE TITLE
Add the "New Book" and "Delete Book" button logic

### ISSUE THREAD

**Issue by SillyPencils** [LazyPencils/JavaFXGroupAssignment#1]
- [x] #5
- [x] Creates new entry on the TableView section. 
- [x] Deletes entries based on whether their check boxes have been selected and ask if user is sure about deleting

**Comment by LazyPencils** [comment]
- [ ] Deletes entry based on whether book is selected inside TableView

**Comment by manhphugiang** [comment]
Manh

**Comment by manhphugiang** [comment]
In order to catch invalid years' input - string, I also make the input fields mandatory for the user to add the year's data.
